name: live_translator_app
description: Mobile version of LiveTranslator for real-time voice translation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  font_awesome_flutter: ^10.5.0
  web_socket_channel: ^2.4.0
  flutter_webrtc: ^0.9.36
  permission_handler: ^10.4.3
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  flutter_sound: ^9.2.13
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/