name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag eiliya/live-translator:latest
    - name: Push the Docker image
      run: |
          docker login  -u eiliya -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push eiliya/live-translator:latest
